[package]
name = "otap-df-contrib-extensions"
description = "OTAP Contrib extensions"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
otap-df-config = { workspace = true }
otap-df-engine = { workspace = true }
otap-df-otap = { workspace = true }
otap-df-telemetry = { workspace = true }
otap-df-telemetry-macros = { workspace = true }

async-trait.workspace = true
futures.workspace = true
linkme.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time", "macros", "rt"] }
tokio-stream = { workspace = true, features = ["sync"] }

azure_core = { workspace = true, optional = true, features = ["reqwest"] }
azure_identity = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true, features = ["rustls-no-provider"] }

[features]
contrib-extensions = ["azure-identity-auth-extension"]
azure-identity-auth-extension = [
    "dep:azure_core",
    "dep:azure_identity",
    "dep:reqwest",
]

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "test-util", "time", "sync"] }
