// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

//! Token provider extension trait.

use std::borrow::Cow;

/// Represents a secret value that should not be exposed in logs or debug output.
///
/// The [`Debug`] implementation will not print the actual secret value.
#[derive(Clone, Eq)]
pub struct Secret(Cow<'static, str>);

impl Secret {
    /// Creates a new `Secret`.
    pub fn new<T>(value: T) -> Self
    where
        T: Into<Cow<'static, str>>,
    {
        Self(value.into())
    }

    /// Returns the secret value.
    #[must_use]
    pub fn secret(&self) -> &str {
        &self.0
    }
}

// Constant-time comparison to prevent timing attacks.
// Note: LLVM may optimize this in unexpected ways.
impl PartialEq for Secret {
    fn eq(&self, other: &Self) -> bool {
        let a = self.secret();
        let b = other.secret();

        if a.len() != b.len() {
            return false;
        }

        a.bytes()
            .zip(b.bytes())
            .fold(0, |acc, (a, b)| acc | (a ^ b))
            == 0
    }
}

impl From<String> for Secret {
    fn from(value: String) -> Self {
        Self::new(value)
    }
}

impl From<&'static str> for Secret {
    fn from(value: &'static str) -> Self {
        Self::new(value)
    }
}

impl std::fmt::Debug for Secret {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Secret")
    }
}

/// Represents a bearer token with its expiration time.
///
/// The token value is wrapped in [`Secret`] to prevent accidental exposure
/// in logs or debug output.
#[derive(Debug, Clone)]
pub struct BearerToken {
    /// The token value.
    pub token: Secret,

    /// The expiration time as a UNIX timestamp (seconds since epoch).
    pub expires_on: i64,
}

impl BearerToken {
    /// Creates a new bearer token.
    pub fn new<T>(token: T, expires_on: i64) -> Self
    where
        T: Into<Secret>,
    {
        Self {
            token: token.into(),
            expires_on,
        }
    }
}

// ── BearerTokenProvider: shared:: + local:: ─────────────────────────────────
//
// Generated by `define_extension_trait!` — one method definition, two
// namespaced traits:
//
// - `shared::BearerTokenProvider: Send + Sync` — `#[async_trait]`, stored as `Arc`
// - `local::BearerTokenProvider` — `#[async_trait(?Send)]`, stored as `Rc`
//
// Implementors opt into whichever they can support:
//
// ```ignore
// // Shared (for shared components, e.g. tonic interceptors):
// #[async_trait]
// impl shared::BearerTokenProvider for MyExt { ... }
//
// // Local (for local components, zero atomic overhead):
// #[async_trait(?Send)]
// impl local::BearerTokenProvider for MyExt { ... }
// ```

super::define_extension_trait! {
    /// A trait for components that can provide bearer authentication tokens.
    ///
    /// Extensions implementing this trait can be looked up by other components
    /// (e.g., exporters) to obtain tokens for authentication.
    ///
    /// # Shared vs Local
    ///
    /// - **`shared::BearerTokenProvider`** (`Send + Sync`) — for shared components
    ///   and thread-safe contexts (tonic interceptors, shared receivers). Stored as
    ///   `Arc<dyn shared::BearerTokenProvider>`.
    ///
    /// - **`local::BearerTokenProvider`** (no bounds) — for local components where
    ///   atomic/mutex overhead matters. Stored as
    ///   `Rc<dyn local::BearerTokenProvider>`. Implementations can use `Rc`,
    ///   `RefCell`, etc.
    ///
    /// # Implementing
    ///
    /// ```ignore
    /// use otap_df_engine::extensions::{shared, local};
    ///
    /// // Shared variant (requires Send + Sync):
    /// #[async_trait]
    /// impl shared::BearerTokenProvider for MyAuthExtension {
    ///     async fn get_token(&self) -> Result<BearerToken, Error> { ... }
    ///     fn subscribe_token_refresh(&self) -> watch::Receiver<Option<BearerToken>> { ... }
    /// }
    ///
    /// // Local variant (no bounds):
    /// #[async_trait(?Send)]
    /// impl local::BearerTokenProvider for MyAuthExtension {
    ///     async fn get_token(&self) -> Result<BearerToken, Error> { ... }
    ///     fn subscribe_token_refresh(&self) -> watch::Receiver<Option<BearerToken>> { ... }
    /// }
    /// ```
    pub BearerTokenProvider {
        /// Returns an authentication token.
        ///
        /// # Errors
        ///
        /// Returns an error if the token cannot be obtained.
        async fn get_token(&self) -> Result<BearerToken, crate::extensions::Error>;

        /// Subscribes to token refresh events.
        ///
        /// Returns a new receiver that will be notified whenever the token
        /// is refreshed. Each call creates an independent subscription.
        /// The receiver always contains the latest token value (or `None`
        /// if no token has been acquired yet).
        fn subscribe_token_refresh(&self) -> tokio::sync::watch::Receiver<Option<BearerToken>>;
    }
}
