// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

//! Re-exports of local (!Send) capability traits and the sealed marker.
//!
//! Canonical definitions live in `crate::capability::<name>::local`.
//! These re-exports let extension authors import via `local::capability::`.

pub use crate::capability::bearer_token_provider::local::BearerTokenProvider;
pub use crate::capability::key_value_store::local::KeyValueStore;

/// Sealed marker for local capability traits.
///
/// Only traits generated by the `#[capability]` proc macro implement this.
/// This ensures `require_local()` only accepts engine-defined capabilities.
#[doc(hidden)]
pub trait Sealed {}
